name: CI/CD Build

on:
  push:
  workflow_dispatch:
  
jobs:
  osx-build:
    name: Build Crown Electrum OSX Asset
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enter Codebase
        run: cd electrum
      
      - name: Rename Constants
        run: python3 buildmatrix_replacer.py Crowncoin
      
      - name: Run Build
        run: ./contrib/osx/make_osx
      
      - name: Package Files for upload
        run: zip -r crown-osx.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: crown-electrum-osx
          path: |
            dist/*	
            crown-osx.zip

  linux-build:
    name: Build Crown Electrum Linux Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enter Code Directory
        run: cd electrum

      - name: Rename Constants
        run: python3 buildmatrix_replacer.py Crowncoin
        
      - name: Install Dependencies
        run: sudo docker build -t electrum-appimage-builder-img contrib/build-linux/appimage
        
      - name: Build project
        run: sudo docker run --name electrum-appimage-builder-cont -v $PWD:/opt/electrum --rm --workdir /opt/electrum/contrib/build-linux/appimage electrum-appimage-builder-img ./build.sh

      - name: Zip Files
        run: zip -r crown-linux.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: crown-electrum-linux
          path: |
            dist/*
            crown-linux.zip
          
  windows-build:
    name: Build Crown Electrum Windows Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enter Code Directory
        run: cd electrum

      - name: Rename Constants
        run: python3 buildmatrix_replacer.py Crowncoin
        
      - name: Install Dependencies
        run: sudo docker build -t electrum-wine-builder-img contrib/build-wine
        
      - name: Build project
        run: sudo docker run --name electrum-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum --rm --workdir /opt/wine64/drive_c/electrum/contrib/build-wine electrum-wine-builder-img ./build.sh

      - name: Zip Files
        run: zip -r crown-windows.zip ./contrib/build-wine/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: crown-electrum-windows
          path: |
            contrib/build-wine/dist/*
            crown-windows.zip
